### ISSUE TITLE
Akka.Hosting support for Akka.Management

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/Akka.Management#738]
**Is your feature request related to a problem? Please describe.**

Once the `Setup` classes et al are polished we should add Akka.Hosting support for:

- [x] Akka.Management (#747)
- [x] Akka.Management.Cluster.Bootstrap (#747)
- Coordination:
  - [x] Akka.Coordination.KubernetesApi (#784)
- Discovery:
  - [x] Akka.Discovery.AwsApi
  - [x] Akka.Discovery.Azure (#747)
  - [x] Akka.Discovery.KubernetesApi

**Describe the solution you'd like**

A composable API system akin to what we've built for Akka.Persistence.

**Describe alternatives you've considered**
N/A

**Additional context**

Do we want to cram all plugins into the same NuGet package? Have Akka.Discovery plugins use their own packages (i.e. same thing we've done for Akka.Persistence?)

**Comment by SeanFarrow** [comment]
Separate NuGet packages would make sense. I'd be happy to help look at this.

**Comment by Aaronontheweb** [comment]
@SeanFarrow we would welcome your help! @Arkatufus is going to spec something out here and stub out the NuGet package - from there we'll need help building the actual APIs themselves.

**Comment by Arkatufus** [comment]
Added a starting PR for Akka.Hosting at https://github.com/akkadotnet/Akka.Management/pull/747

**Comment by SeanFarrow** [comment]
Brilliant, what help do you need from here?

**Comment by Arkatufus** [comment]
@SeanFarrow 

I've added a checklist/tasks of things that needed to be added in the issue description above, we'll check them as complete when the related PRs have been merged.
So far, we still need to add `Coordination.KubernetesApi`, `Discovery.AwsApi`, and `Discovery.KubernetesApi` support.

Thanks for the help :)

**Comment by SeanFarrow** [comment]
OK, is it best to start with discovery.KubernetesApi, or Coordination.KubernetesApi?
What’s the difference between the discovery and coordination sides of this?
No worries, I love to help where I can and have wanted to for a while.

Thanks,
Sean.

**Comment by Arkatufus** [comment]
Discovery is probably the easier one. 
Discovery helps with automated cluster formation, while Coordination handles managed leases for things like shared resource locking in a cloud/distributed system. 
For example, an actor in node A can claim exclusive use of a cloud resource by claiming a lease, other nodes in the cluster would not be able to access the same resource until node A releases the claimed lease.

**Comment by SeanFarrow** [comment]
Ah, OK, that makes sense.
I’ll start work on the k8s discovery project/package this weekend.
Thanks,
Sean.

**Comment by SeanFarrow** [comment]
@Aaronontheweb, @Arkatufus ,
Whilst writing the tests for the K8s discovery code, I wondered whether we want to spin up a cluster and if yes, how we want to do this on multiple operating systems, given they each have different ways of doing things (docker for windows, kind, minikube etc) and we need to support locally running the tests, or whether just resolving the actor system from the service provider and validating the  config is enough?

In an ideal world, I'd go for the former, if we were fully in control of peple's systems, but given this is an open source project, we can't assume anything in terms of a users environment--do they have docker installed etc.

Finally, we also need to consider what facilities the Azure CI agents have on them, but can determine whether we are running in CI/CD using an environment variable.

Your thoughts/opinions would be most welcome.

**Comment by Aaronontheweb** [comment]
@SeanFarrow for K8s tests today I believe we just mock the K8s API server response objects, since spinning up a real K8s cluster is probably a non-starter in our CI systems:

https://github.com/akkadotnet/Akka.Management/blob/7ba95d7b1b0d8599bbb142457e451d98b51d86e2/src/discovery/kubernetes/Akka.Discovery.KubernetesApi.Tests/KubernetesApiServiceDiscoverySpec.cs#L25-L65

You could re-use an approach similar to this one in the .Hosting specs.

**Comment by SeanFarrow** [comment]
@Aaronontheweb 
OK, I'll follow that.

Thanks,
Sean.

**Comment by Aaronontheweb** [comment]
@Arkatufus can give you some pointers on how to do that if you need help @SeanFarrow
